### ISSUE TITLE
Error editing works that have a location from geonames

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyrax#1066] opened 2017-05-26 15:59 UTC
### Descriptive summary

Discovered when testing Hyku Beta (Hyku v1.0.0.beta1) is using hyrax (2.0.0.alpha). Trying to edit an existing work that already has a location property results in an error.

![image](https://cloud.githubusercontent.com/assets/722117/26502330/61179204-4234-11e7-9743-42d0585b90d9.png)

I have not tested this in a plain hyrax app.

### Rationale

This is a bug and prevents editing of any works that contain a location.

### Expected behavior

Edit of works is possible.

### Actual behavior

Hitting 'Edit' results in an error.

### Steps to reproduce the behavior

1. Clone Hyku master and follow steps to run the app: https://github.com/samvera-labs/hyku 
1. Create a work with a location selected from the Geonames auto-suggest.

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment] 2017-06-01 19:30
Confirmed. https://app.honeybadger.io/projects/48327/faults/33745862

**Comment by no-reply** [comment] 2017-06-01 21:23
It looks like `multi_value_input.rb`'s call to `#build_field` gives a `ActiveTriples::Relation` where the expected `value` is an `ActiveTriples::RDFSource`. Either the caller or `build_field` needs to iterate the values in the relation.

You can assign this to me, but it would be mid-to-late next week before I get to it.

**Comment by geekscruff** [comment] 2017-06-02 09:25
The field is behaving as a single rather than a multi-input field - you can only add one location. Is that intended behaviour? If not, it would be nice to make this behave as a multi-input field as part of the fix.

**Comment by jcoyne** [comment] 2017-06-02 16:17
@geekscruff yes, that's a separate issue. Can you open a new ticket for that?

**Closed** 2017-06-02 20:08 UTC
Labels: bug, in progress, metadata, ready
